USE db1;

ALTER TABLE PRODUCTS
    ADD COLUMN status ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE';

ALTER TABLE CATEGORIES
    ADD COLUMN status ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE';

ALTER TABLE BRANDS
    ADD COLUMN status ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE';
